### ISSUE TITLE
[BUG]: Link appearing when display=none

### ISSUE THREAD

**Issue by ianTevesAcc** [johansatge/obsidian-automatic-table-of-contents#47]
Higher rank css rules over power the css rule of <a> link causing the display none to be shown.
We should probably add `display: none !important;` for the link so that its not over ruled by previous rules. 

![image](https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/105651670/debf47a2-9328-4f92-9c83-e03985524863)

Solved with a bit of css.
```css
.block-language-table-of-contents li a[style="display: none;"] {
    display: none !important;
}
```

```table-of-contents
title: 
style: nestedOrderedList # TOC style (nestedList|nestedOrderedList|inlineFirstLevel)
minLevel: 0 # Include headings from the specified level
maxLevel: 0 # Include headings up to the specified level
includeLinks: true # Make headings clickable
debugInConsole: false # Print debug info in Obsidian console
```

Checklist:
- [x] Check in the readme if the bug is linked to a documented limitation
- [x] Describe what the bug is
- [x] Paste a Markdown block that helps reproducing the described issue
- [x] Upload a screenshot with the rendered result if relevant
- [-] Describe the environment (OS, Obsidian version, installed plugins)

**Comment by ianTevesAcc** [comment]
You can work around this bug by adding the following css snippet:
```css
.workspace-leaf-content[data-mode="source"] .block-language-table-of-contents li a[style="display: none;"] {
    display: none !important;
}
```

This disables the link when not in source view.
